services:

  leader:
    image: cribl/cribl:latest
    container_name: cribl-leader
    ports:
      - 19000:9000
    network_mode: host
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && exec tail -f /dev/null"]
    tty: true
    init: true
    environment:
      - CRIBL_DIST_MODE=leader
      - CRIBL_DIST_LEADER_URL=tcp://${CRIBL_DIST_TOKEN:-criblmaster}@0.0.0.0:4200
      - CRIBL_VOLUME_DIR=/opt/cribl/config-volume
    volumes:
      - "~/cribl-config:/opt/cribl/config-volume"

  worker:
    image: cribl/cribl:latest
    container_name: cribl-worker
    depends_on: 
      - leader
    ports:
      - 9000
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl vim && exec tail -f /dev/null"]
    tty: true
    init: true
    environment:
      - CRIBL_DIST_MODE=worker
      - CRIBL_VOLUME_DIR=/opt/cribl
      - CRIBL_DIST_LEADER_URL=tcp://${CRIBL_DIST_TOKEN:-criblmaster}@leader:4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - worker:/opt/cribl

networks:
  criblcandidatenetwork:

volumes:
  leader:
  worker:
